### PR TITLE
Improve recovering after db failure: covered SocketTimeoutException

### PR DESCRIPTION
**Pull request by echipachenko**
Improve recovering after DB failure: covered SocketTimeoutException case, when DB response might not be read because of slow network connections (or data loss).

We faced an issue when the queue poller stops work after a network issue.

This PR should fix the issue

### CODE REVIEW

**Comment by echipachenko** [comment]
Hi @marcanpilami 
Please review my PR.
It should fix the queue poller recovery problem, when it can't recover itself, after socket timeout exception, caused be network data packet lose.

**Comment by echipachenko** [comment]
CC: @marcanpilami

**Comment by marcanpilami** [comment]
I do hesitate to merge this - this is actually already handled inside ongoing PR https://github.com/enioka/jqm/pull/368, which is not targeted for 2.x for only for 3.x. (it is actually a bigger overhaul, with exception analysis being delegated to the database connector and not to a weird shared static method). Is it a crucial need for you in 2.x ?

**Comment by echipachenko** [comment]
Hi @marcanpilami 
Currently, we have several production incidents, related to this problem.
For us, it's really important to have correct database exception handling.

**Comment by iherasymenko** [comment]
@marcanpilami like @echipachenko mentioned before, we've been hit by the issue several times and on a scale of 500 installation, this becomes extremely critical to us. We would appreciate if you reconsider and include this fix in 2.2. Thank you.

**Comment by marcanpilami** [comment]
Thanks for the PR. Marked for 2.2.8 release. This Apache util makes wonders for code clarity, thanks for showing it to us.

**Pull request merged**
