### PR TITLE
JQM API Extension: add possibility to query current queue capacity around active nodes

### PR DESCRIPTION
**Pull request by echipachenko**

### CODE REVIEW

**Comment by echipachenko** [comment]
Hi @marcanpilami !
Please review this PR.
When you merge it - please, upload new snapshot to the Sonatype

**Comment by marcanpilami** [comment]
Hi, thanks for the contribution. In your query, you just look at queue mappings - but actually the node itself can also be disabled, so I would add a LEFT JOIN NODE and check the node status too.

Also, I would rename the API verb from getQueueCapacity to getQueueEnabledCapacity to make it very clear it is not the theoretical or free capacity.

**Comment by echipachenko** [comment]
Hi @marcanpilami !
I had updated my pull-request, please review it.

**Comment by echipachenko** [comment]
updated

**Comment by echipachenko** [comment]
Hi @marcanpilami ! What about this pull request? Will you merge it?

**Pull request merged**
